
GET http://127.0.0.1:9000/member/member/count
Accept: application/json

###

POST http://127.0.0.1:9000/member/member/registry
Content-Type: application/json

{
  "mobile": "13800138000"
}

###

POST http://127.0.0.1:9000/member/member/send-code
Content-Type: application/x-www-form-urlencoded

mobile = 18784678734

###

POST http://127.0.0.1:9000/member/member/login
Content-Type: application/json

{
  "mobile": "13800138000",
  "code": "8888"
}